[package]
name = "day-6"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day-6-1"
path = "src/main1.rs"

[[bin]]
name = "day-6-2"
path = "src/main2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
